# Specification for resolving avatar mannequins
resolution_strategy: "singleton"

sources:
  - { name: "mannequinObjects", type: "cdn", path: "avatar_all", sub_key: "mannequinObjects" }
  - { name: "mannequinStands", type: "cdn", path: "avatar_all", sub_key: "mannequinStands" }
  - { name: "partsMannequins", type: "cdn", path: "avatar_all", sub_key: "partsMannequins" }

output_structure:
  mannequin:
    type: "object"
    fields:
      mannequinObjects: { type: "list", from: "mannequinObjects" }
      mannequinStands: { type: "list", from: "mannequinStands" }
      partsMannequins: { type: "list", from: "partsMannequins" }
