# You can use %archive% to point to the source_archives directory.
# Example: %archive%/1.3.0.0__t.zip/survival
local_data_paths:
  cdn: 'data\web_avatar\avatar_all.json'
  manual: 'data\manual'
  survival: 'source_archives\1.3.0.0__asarai.zip\1'
